- name: SSH Server Config | Ensure ssh keys are present
  authorized_key:
    user: scorch
    key: "{{ lookup('file', item) }}"
    state: present
    exclusive: False
  with_fileglob:
    - public_keys/scorch*.pub
  tags:
    - step5
    - ssh

- name: SSH Server Config | Hardening
  template:
    src: etc/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  become: yes
  tags:
    - step5
    - ssh

- name: SSH Server Config | Reload sshd.service
  service:
    name: ssh
    state: reloaded
  become: true
